name: vm_aprende_sim
description: Aplicativo educacional e simulador dinamico de ventilacao mecanica invasiva e nao invasiva.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1

flutter:
  uses-material-design: true
